#![feature(trait_alias)]

#![feature(test)]
extern crate test;

#[macro_use] mod imports;
use imports::*;

x!{async_error}
x!{async_error_net}
x!{async_net_base}
x!{async_net_cancelled}
x!{async_net_executor_helper}
x!{async_scheduling}
x!{async_task}
x!{async_task_future}
x!{async_task_graph}
x!{async_task_graph_base}
x!{chain_error_net}
x!{check_chaining_and_run}
x!{compute_chains}
x!{compute_groups}
x!{compute_input_size}
x!{create}
x!{create_net}
x!{create_net_test_helper}
x!{create_operator}
x!{dag_util_test_context}
x!{declare}
x!{declare_registry}
x!{define}
x!{define_tensor_types_dispatcher}
x!{device_type_registerer}
x!{device_type_registry}
x!{dispatch_helper}
x!{dummy_async}
x!{dummy_observer}
x!{dummy_sync}
x!{engine_pref_type}
x!{execution_options}
x!{executor_helper}
x!{executor_helper_dummy_op}
x!{external_tensor_descriptor}
x!{external_tensor_functions}
x!{get_async_net_thread_pool}
x!{get_counter_for_net_name}
x!{get_gradient_for_op}
x!{get_registered_operators}
x!{gradient}
x!{gradient_helpers}
x!{gradient_maker_base}
x!{gradient_maker_storage}
x!{gradient_not_impl}
x!{gradient_ops_meta}
x!{gradient_traits}
x!{gradient_wrapper}
x!{individual_metrics}
x!{infer_blob_shapes}
x!{infer_blob_shapes_and_types}
x!{inference_function_types}
x!{load_from_blob}
x!{net_base}
x!{net_simple_refcount_test}
x!{net_test_dummy_op}
x!{not_finishing_op}
x!{observable}
x!{observer}
x!{observer_base}
x!{observer_time_observer_test}
x!{op_registry}
x!{operator_attaching_net_observer}
x!{operator_logger}
x!{operator_node}
x!{operator_registry}
x!{operator_schema}
x!{operator_schema_argument}
x!{operator_schema_cost}
x!{operator_schema_registry}
x!{operator_schema_support}
x!{operator_storage}
x!{overrides}
x!{parallel_net}
x!{parallel_net_executor_helper}
x!{parent_counter}
x!{prepare_chain_graph_nodes}
x!{prepare_operator_nodes}
x!{print_chains}
x!{profile_counter}
x!{profile_observer}
x!{profile_operator_observer}
x!{prune}
x!{register}
x!{runcount_operator_observer}
x!{shard_id}
x!{simple_net}
x!{simple_ref_count_net}
x!{single_chains}
x!{sleep_op}
x!{start_iter}
x!{static_linking_protector}
x!{stop_on_signal}
x!{sync_error}
x!{tensor_types}
x!{test_dag_util}
x!{test_execution}
x!{test_gpu_operator}
x!{test_net}
x!{test_net_simple_refcount}
x!{test_observer}
x!{test_operator}
x!{test_operator_schema}
x!{test_parallel_net}
x!{test_tracing}
x!{test_workspace}
x!{time_counter}
x!{time_observer}
x!{time_operator_observer}
x!{towel}
x!{trace}
x!{traceable}
x!{tracer}
x!{tracer_event}
x!{tracer_guard}
x!{tracing_config}
x!{tracing_field}
x!{tracing_mode}
x!{trait_add_related_blob_info}
x!{trait_cancel}
x!{trait_check_argument_with_name}
x!{trait_check_async}
x!{trait_check_io_is_type}
x!{trait_check_io_size}
x!{trait_check_is_io_alias}
x!{trait_check_legacy_operator}
x!{trait_check_stream}
x!{trait_check_stream_fee}
x!{trait_debug}
x!{trait_engine}
x!{trait_event}
x!{trait_executor_helper}
x!{trait_external_tensor_functions}
x!{trait_finish}
x!{trait_get_context}
x!{trait_get_device_option}
x!{trait_get_error_message}
x!{trait_get_function_schema}
x!{trait_get_inputs}
x!{trait_get_io_blob}
x!{trait_get_output_at_index}
x!{trait_get_outputs}
x!{trait_get_repeated_argument}
x!{trait_get_single_argument}
x!{trait_get_type}
x!{trait_get_vector}
x!{trait_move_newstyle_outputs}
x!{trait_net_position}
x!{trait_operator}
x!{trait_record}
x!{trait_run}
x!{trait_run_async_stream}
x!{trait_run_stream}
x!{trait_set_event_finished}
x!{trait_set_output_tensor}
x!{trait_sync_device_barrier}
x!{trait_wait}
x!{trait_wait_event}
x!{trait_wait_events}
x!{unsupported_operator_feature}
x!{update_operator_nodes}
x!{validate_tensor_devices}
x!{workspace}
x!{workspace_bookkeeper}
