#[macro_use] mod imports; use imports::*;

x!{advanced_indexing}
x!{checked_from}
x!{arange}
x!{bartlett}
x!{blackman}
x!{check}
x!{clone}
x!{compare}
x!{complex}
x!{conversions}
x!{dim_apply}
x!{dispatch}
x!{empty}
x!{eye}
x!{from_file}
x!{full}
x!{hamming}
x!{hann}
x!{iterator_dynamic_casting}
x!{iterator_reduce}
x!{kaiser}
x!{linspace}
x!{logspace}
x!{normal}
x!{ones}
x!{op_list}
x!{operators}
x!{polar}
x!{properties}
x!{rand_factory}
x!{randint}
x!{randn}
x!{randperm}
x!{range}
x!{register_backend_select}
x!{register_dispatch_key}
x!{register_schema}
x!{scalar}
x!{reshape}
x!{tensor}
x!{tensor_body}
x!{tensor_functions}
x!{tensor_geometry}
x!{tensor_impl_test}
x!{tensor_indexing}
x!{tensor_iterator}
x!{tensor_iterator_internal}
x!{tensor_meta}
x!{tensor_methods}
x!{tensor_names}
x!{tensor_operators}
x!{tensor_utils}
x!{transformations}
x!{triangle}
x!{vandermonde}
x!{window}
x!{xla_type_default}
x!{zeros}
x!{dimname}
