#[macro_use] mod imports; use imports::*;

x!{ops_common}
x!{ops_copy_}
x!{ops_tensor}
x!{api_runtime}
x!{vulkan}
x!{ops_mean}
x!{api_pipeline}
x!{api_adapter}
x!{ops_factory}
x!{vulkan_ops}
x!{api_descriptor}
x!{api_command}
x!{api_vk_mem_alloc}
x!{vulkan_convolution}
x!{vulkan_op_context}
x!{vulkan_context}
x!{vulkan_guard_impl}
x!{ops_persistent}
x!{api_cache}
x!{vulkan_register_op_context_class}
x!{ops_pool}
x!{api_common}
x!{api_utils}
x!{ops_clamp}
x!{ops_utils}
x!{vulkan_aten}
x!{ops_padding}
x!{vulkan_opaque_tensor_impl}
x!{ops_convolution}
x!{ops_shape}
x!{api_allocator}
x!{ops_upsample}
x!{api_shader}
x!{ops_arithmetic}
x!{ops_mm}
x!{vulkan_common}
x!{api_resource}
x!{ops_register}
x!{api_context}
