#![feature(specialization)]

#![feature(test)]
extern crate test;

#[macro_use] mod imports;
use imports::*;

x!{add}
x!{annotation}
x!{average_pool_relu}
x!{average_pool}
x!{basic_block}
x!{batch_normalization}
x!{binary_match}
x!{branch}
x!{channel_shuffle}
x!{clip}
x!{coalesce}
x!{concat}
x!{consumer}
x!{control_flow_graph}
x!{conv_relu}
x!{conv_transpose}
x!{convert_graph_to_dot}
x!{convert_node}
x!{conv}
x!{copy_from_opencl}
x!{copy_to_opencl}
x!{create_graph}
x!{create_subgraph}
x!{data}
x!{declare}
x!{delete}
x!{dominator_map}
x!{dominator_tree}
x!{dot_generator}
x!{edge}
x!{export}
x!{fc}
x!{flatten}
x!{generic_operator}
x!{get_tracked_nodes}
x!{given_tensor_fill}
x!{graph_wrapper}
x!{induce_edges}
x!{inherited_from}
x!{inputs}
x!{insert_op}
x!{instruction}
x!{iterator}
x!{match_graph}
x!{match_predicate}
x!{max_pool_relu}
x!{max_pool}
x!{name}
x!{nchw2nhwc}
x!{nn_equality}
x!{nn_match}
x!{nn_module}
x!{nn_operator}
x!{nn_while}
x!{nndata}
x!{nnkind}
x!{nnrtti}
x!{node_equality}
x!{node_wrapper}
x!{nom_graph}
x!{nom_node}
x!{notifier}
x!{outputs}
x!{phi}
x!{printer}
x!{producer}
x!{reachable}
x!{receive}
x!{relu}
x!{replace}
x!{reshape}
x!{return_terminator}
x!{send}
x!{softmax}
x!{storage_type}
x!{subgraph_match_result}
x!{subgraph}
x!{sum_relu}
x!{sum}
x!{support}
x!{tarjans}
x!{tensor}
x!{terminator}
x!{test_binary_match}
x!{test_dominator_tree}
x!{test_dot}
x!{test_match_basic}
x!{test_random}
x!{test_replace_graph}
x!{test_subgraph_induce}
x!{test_subgraph_matcher}
x!{test_tarjan}
x!{topo_sort}
x!{toposort}
x!{value}
