#![feature(test)]
extern crate test;

#[macro_use] mod imports;
use imports::*;

x!{adam}
x!{adam_compute}
x!{adam_compute_grad}
x!{adam_update}
x!{canonical_dims}
x!{channel_shuffle}
x!{channel_shuffle_gradient}
x!{concat}
x!{context}
x!{conv}
x!{conv_fusion}
x!{conv_gradient}
x!{conv_pool_base}
x!{conv_transpose}
x!{conv_transpose_gradient}
x!{conv_transpose_unpool_base}
x!{convert_scales}
x!{copy}
x!{copy_bytes}
x!{copy_cpu_to_ideep}
x!{copy_ideep_to_cpu}
x!{create_blobs_queue}
x!{def_aliases}
x!{dropout}
x!{dropout_gradient}
x!{elementwise_sum}
x!{expand_dims}
x!{fallback_op}
x!{fully_connected}
x!{fully_connected_gradient}
x!{i8_conv}
x!{i8_conv_relu}
x!{i8_conv_sum}
x!{i8_conv_sum_relu}
x!{i8_dequantize}
x!{i8_fully_connected}
x!{i8_given_int_tensor_fill}
x!{i8_given_tensor_fill}
x!{i8_pool}
x!{i8_quantize}
x!{i8_relu}
x!{i8_sum_relu}
x!{local_response_normalization}
x!{local_response_normalization_gradient}
x!{momentum_sgd}
x!{momentum_sgd_update}
x!{momentum_sgd_update_compute}
x!{opertor}
x!{order_switch}
x!{pool}
x!{pool_gradient}
x!{register}
x!{relu}
x!{relu_gradient}
x!{reshape}
x!{safe_enqueue_blobs}
x!{shape}
x!{sigmoid}
x!{sigmoid_gradient}
x!{spatial_batch_norm}
x!{spatial_batch_norm_gradient}
x!{split}
x!{squeeze}
x!{transpose}
x!{types}
x!{weighted_sum}
