#[macro_use] mod imports; use imports::*;

x!{test_native_test}
x!{test_operators_test}
x!{test_tensor_iterator_test}
x!{test_variant_test}
x!{test_named_tensor_test}
x!{test_cuda_tensor_interop_test}
x!{test_xla_tensor_test}
x!{test_pow_test}
x!{test_vitals}
x!{test_cpu_caching_allocator_test}
x!{test_ivalue_test}
x!{test_quantized_test}
x!{test_memory_overlapping_test}
x!{test_atest}
x!{test_type_test}
x!{test_broadcast_test}
x!{test_tensor_interop_test}
x!{test_rng_test}
x!{test_extension_backend_test}
x!{test_basic}
x!{test_vulkan_test}
x!{test_apply_utils_test}
x!{test_cuda_cudnn_test}
x!{test_exclusively_owned_test}
x!{test_wrapdim_test}
x!{test_dlconvertor_test}
x!{test_undefined_tensor_test}
x!{test_test_thread_pool_guard}
x!{test_vmap_test}
x!{test_cuda_stream_test}
x!{test_maybe_owned_test}
x!{test_cuda_dlconvertor_test}
x!{test_cpu_rng_test}
x!{test_dimname_test}
x!{test_vulkan_api_test}
x!{test_test_parallel}
x!{test_cpu_generator_test}
x!{test_dict_test}
x!{test_memory_format_test}
x!{test_mobile_memory_cleanup}
x!{test_xnnpack_test}
x!{test_reduce_ops_test}
x!{test_cpu_profiling_allocator_test}
x!{test_test_assert}
x!{test_half_test}
x!{test_weakref_test}
x!{test_scalar_tensor_test}
x!{test_cuda_apply_test}
x!{test_test_install_main}
x!{test_math_kernel_test}
x!{test_scalar_test}
x!{test_thread_init_test}
x!{test_vec_test_all_types}