#[macro_use] mod imports; use imports::*;

x!{thc_thc_allocator}
x!{th_generic_th_tensor_math}
x!{thc_generic_thc_tensor_math_pairwise}
x!{thc_thc_tensor}
x!{thc_generic_thc_tensor}
x!{thc_thc_generate_all_types}
x!{th_th_vector}
x!{th_generic_th_tensor_apply}
x!{th_generic_th_tensor}
x!{thc_generic_thc_tensor_scatter_gather}
x!{thc_generic_thc_tensor_math}
x!{thcunn_generic}
x!{thcunn_common}
x!{th_th_storage_functions}
x!{thc_generic_thc_tensor_math_pointwise}
x!{th_generic_th_storage_copy}
x!{thc_generic_thc_tensor_math_magma}
x!{th_generic_th_blas}
x!{th_generic_th_storage}
x!{th_th_tensor}
x!{th_th_tensor_apply}
x!{thcunn}
x!{thc_thc_storage}
x!{th_th_general}
x!{thc_thc_sleep}
x!{th_th_blas}
x!{thc_thc_caching_host_allocator}
x!{legacy_thf_unctionscuda}
x!{thc_thc_general}
x!{legacy_thf_unctions_cpu}
x!{thc_generic_thc_storage}
x!{th_generic_th_tensor_fast_get_set}
x!{thc_generic_thc_storage_copy}
x!{thc_thc_tensor_math_magma}
x!{th_th_allocator}
x!{th_generic_th_vector}
x!{th_th_tensor_dim_apply}
x!{th_generic_th_tensor_more_math}
x!{thc_generic_thc_tensor_copy}
x!{legacy_th_functionscuda}
