#[macro_use] mod imports; use imports::*;

x!{qlinear_unpack}
x!{make_per_tensor_quantized_tensor}
x!{qconv}
x!{qpool}
x!{qhardswish}
x!{qconv_prepack}
x!{qconcat}
x!{tensor_operators}
x!{qlinear_dynamic}
x!{q_avgpool3d}
x!{q_adaavgpool}
x!{qlinear_prepack}
x!{qupsample_nearest3d}
x!{quantized_ops}
x!{qreduction}
x!{qnormalization}
x!{qconv_unpack}
x!{qhardsigmoid}
x!{qupsample_nearest2d}
x!{fbgemm_utils}
x!{qupsample_bilinear2d}
x!{qlinear}
x!{embedding_packed_params}
x!{qrelu}
x!{kernels_quantized_op_kernels}
x!{qadd}
x!{int_repr_quant}
x!{qchannel_shuffle}
x!{qelu}
x!{qsort}
x!{conv_packed_params}
x!{q_avgpool}
x!{qsigmoid}
x!{qbatch_norm}
x!{packed_params}
x!{qmul}
x!{init_qnnpack}
x!{qembeddingbag}
x!{quant_utils}
x!{qtanh}
x!{conv_serialization}
x!{qembeddingbag_prepack}
x!{qembeddingbag_unpack}
x!{qclamp}
x!{qthreshold}