#![feature(test)]
extern crate test;

#[macro_use] mod imports;
use imports::*;

x!{accumulate_histogram}
x!{alias}
x!{ensure_dense}
x!{fail}
x!{flatten_to_vec}
x!{gather_ranges}
x!{get_alias_gradient}
x!{get_ensure_dense_gradient}
x!{get_flatten_to_vec_gradient}
x!{get_nan_check_gradient}
x!{get_sum_gradient}
x!{get_weighted_sum_gradient}
x!{has_elements}
x!{inference}
x!{is_nan}
x!{lengths_gather}
x!{lengths_to_offsets}
x!{lengths_to_ranges}
x!{lengths_to_segment_ids}
x!{lengths_to_shape}
x!{lengths_to_weights}
x!{log_fatal}
x!{nan_check}
x!{nan_check_cpu}
x!{no_default_engine}
x!{print}
x!{range}
x!{range_cpu}
x!{register}
x!{resize_like}
x!{run_accumulate_histogram}
x!{run_gather_ranges}
x!{run_lengths_gather}
x!{run_range}
x!{scatter}
x!{scatter_assign}
x!{scatter_weighted_sum}
x!{segment_ids_to_lengths}
x!{segment_ids_to_ranges}
x!{size}
x!{sum_op}
x!{test_flatten_to_vec}
x!{test_gather_ranges}
x!{test_has_elements}
x!{test_lengths_gather}
x!{test_lengths_to_segment_ids}
x!{test_lengths_to_shape}
x!{test_range}
x!{test_size}
x!{throw_child_thread_exception}
x!{throw_exception}
x!{tset_reshape}
x!{wallclock_time}
x!{weighted_sum}
x!{weighted_sum_cpu}
x!{weighted_sum_gradient}
x!{weighted_sum_gradient_cpu}
