#![feature(test)]
extern crate test;

#[macro_use] mod imports;
use imports::*;

x!{base_reducer}
x!{base_reducer_gradient}
x!{base_reducer_gradient_meta}
x!{base_reducer_meta}
x!{colwise_max}
x!{compute_reduce_minmax_gradient}
x!{get_colwise_max_gradient}
x!{get_gradient}
x!{get_rowwise_max_gradient}
x!{get_sum_element_gradient}
x!{inference}
x!{l1_reduce}
x!{l1_reduce_cpu}
x!{l2_reduce}
x!{l2_reduce_cpu}
x!{log_mean_exp_range_reducer}
x!{log_mean_exp_range_reducer_def}
x!{log_mean_exp_range_reducer_gradient}
x!{log_sum_exp_range_reducer}
x!{log_sum_exp_range_reducer_def}
x!{log_sum_exp_range_reducer_gradient}
x!{max_range_reducer}
x!{max_range_reducer_def}
x!{max_range_reducer_gradient}
x!{max_reduce}
x!{max_reduce_cpu}
x!{max_reduce_dims}
x!{max_reduce_dims_cpu}
x!{max_reduce_dims_gradient}
x!{max_reduce_dims_gradient_cpu}
x!{max_reducer}
x!{max_reducer_def}
x!{max_reducer_gradient}
x!{max_reduction}
x!{max_reduction_gradient}
x!{mean_range_reducer}
x!{mean_range_reducer_def}
x!{mean_range_reducer_gradient}
x!{mean_reduce}
x!{mean_reducer}
x!{mean_reducer_def}
x!{mean_reducer_gradient}
x!{min_reduce}
x!{min_reduce_cpu}
x!{reduce}
x!{reduce_back_max_config}
x!{reduce_config}
x!{reduce_front_max_config}
x!{reduce_gradient}
x!{reduce_l1_config}
x!{reduce_l2_config}
x!{reduce_max_config}
x!{reduce_mean_config}
x!{reduce_min_config}
x!{reduce_shape_inference}
x!{reduce_sum_config}
x!{reducer}
x!{register}
x!{rowwise_max}
x!{sum_elements}
x!{sum_elements_config}
x!{sum_elements_gradient}
x!{sum_elements_int}
x!{sum_range_reducer}
x!{sum_range_reducer_def}
x!{sum_range_reducer_gradient}
x!{sum_reduce}
x!{sum_reduce_dims}
x!{sum_reduce_dims_cpu}
x!{sum_reduce_dims_gradient}
x!{sum_reduce_dims_gradient_cpu}
x!{sum_reducer}
x!{sum_reducer_def}
x!{sum_reducer_gradient}
x!{sum_sqr_elements}
x!{sum_sqr_elements_config}
x!{test_colwise_max}
x!{test_reduce}
x!{test_reduce_l1}
x!{test_reduce_l2}
x!{test_reduce_mean}
x!{test_reduce_sum}
x!{test_rowwise_max}
x!{test_sum_elements}
x!{weighted_sum_reducer}
x!{weighted_sum_reducer_def}
x!{weighted_sum_reducer_gradient}
x!{weighted_sum_reducer_gradient_meta}
x!{weighted_sum_reducer_meta}
