#![feature(test)]
extern crate test;

#[macro_use] mod imports;
use imports::*;

x!{add_blob_device_options}
x!{add_converter}
x!{add_nnpack}
x!{adjust_quantized}
x!{alloc}
x!{annotation}
x!{ast_expr}
x!{ast_graph}
x!{ast_stmt}
x!{average_pool_converter}
x!{backend_transform_options}
x!{backend_transformer_base}
x!{backend_transformer_base_trait}
x!{batch_mat_mul_converter}
x!{blob_to_tensor_descriptor}
x!{bound_shape_inference_base_trait}
x!{bound_shape_inferencer}
x!{bound_shape_spec}
x!{cast_converter}
x!{check_net}
x!{check_shape_info}
x!{clip_converter}
x!{clip_ranges_converter}
x!{clip_ranges_gather_sigrid_hash_converter}
x!{clip_ranges_gather_sigrid_hash_v2_converter}
x!{collect_inputs_and_outputs}
x!{compose_result_net}
x!{compute_dedup_rename_map}
x!{concat_add_mul_replace_nan_clip}
x!{concat_add_mul_replace_nan_clip_converter}
x!{concat_converter}
x!{concat_elim}
x!{conv_converter}
x!{conv_transpose_converter}
x!{convert}
x!{convert_to_c2net}
x!{convert_to_neural_net_operator}
x!{convert_to_nn_module}
x!{convert_to_nqlstring}
x!{convert_to_operator_def}
x!{convert_to_value_info}
x!{convert_to_vec}
x!{converter}
x!{copy_descriptor}
x!{dead_code_elim}
x!{define}
x!{detect_boundary_references}
x!{dump_graph}
x!{enforce_fp32_inputs}
x!{explore}
x!{fakefp16_transform}
x!{fc_converter}
x!{fetch_inputs_to_if_ops_subnet}
x!{fill_model_info}
x!{freeze_quantization_params}
x!{fuse_activation}
x!{fuse_cat_batch_one_hot}
x!{fuse_nnpack_conv_relu}
x!{get_annotation}
x!{get_blob}
x!{get_dilations}
x!{get_group}
x!{get_info}
x!{get_io_edges}
x!{get_layout}
x!{get_name_for_blob}
x!{get_node_name}
x!{get_onnxifi_data_type}
x!{get_pads}
x!{get_strides}
x!{get_weights_and_input}
x!{graph_matcher}
x!{group_annotation}
x!{in_batch_broadcast}
x!{inject}
x!{insert_copies}
x!{is_nnpack_conv_relu_efficient}
x!{make_tensor_info}
x!{map_onnx_status_to_string}
x!{matched_subgraph}
x!{max_pool_converter}
x!{merge_external_tensors}
x!{merge_fp32_inputs}
x!{mul_converter}
x!{onnx_annotation}
x!{onnxifi}
x!{onnxifi_data_type}
x!{onnxifi_op}
x!{onnxifi_option_helper}
x!{onnxifi_transformer}
x!{onnxifi_transformer_options}
x!{onnxifi_type}
x!{optimization_passes}
x!{optimize_for_backend}
x!{optimize_ideep}
x!{optimizer}
x!{output_reshape}
x!{parallelization}
x!{parse_block_list_ops}
x!{parse_net_position_list}
x!{prune_unreferenced_nodes}
x!{push_op_to_front}
x!{register_converter}
x!{remove}
x!{replace_nan_converter}
x!{replace_subgraph}
x!{set_device_option}
x!{set_input_tensor_descriptor}
x!{set_output_tensor_descriptor}
x!{shape_info}
x!{show_node}
x!{sigrid_hash_converter}
x!{size_to_dim}
x!{slice_converter}
x!{split_sparse_lengths_sum_sparse}
x!{strip_shape_info_map}
x!{take_precedence_over}
x!{tensor_info}
x!{test_backend_cutting}
x!{test_batch_broadcast}
x!{test_bound_shape_inference}
x!{test_converter}
x!{test_custom_concat}
x!{test_custom_converter}
x!{test_dead_code_elim}
x!{test_device}
x!{test_distributed}
x!{test_graphmatcher}
x!{test_match_predicate}
x!{test_mobile_conv}
x!{test_split_slss}
x!{transform_subgraph}
x!{tvm_transformer}
x!{verify_shape_info}
x!{visitor_context}
x!{wrap_shape}
